# Generated by Django 4.1.5 on 2023-01-07 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0002_entry_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
